### ISSUE TITLE
When snapshot update fails, not only assets but also report should be uploaded

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/maintainer-tools#191]
### Problem

Snapshots on my PR are failing prior to taking a snapshots which I cannot repro locally. The PR job contains both assets and snapshots but the update job only assets, compare:

![Screenshot from 2023-04-14 18-22-29](https://user-images.githubusercontent.com/5832902/232114303-b6b160ad-c324-41d0-9243-8115c5b7d57e.png)
from https://github.com/jupyterlab/jupyterlab/actions/runs/4682777719?pr=14356

with

![Screenshot from 2023-04-14 18-22-36](https://user-images.githubusercontent.com/5832902/232114336-779d85f1-7b64-475d-82dc-f8e8393425f1.png)
from https://github.com/jupyterlab/jupyterlab/actions/runs/4682788709

### Proposed Solution

Upload both on failure

### Additional context

In lab repo we use:

```
      - name: Upload Galata Test assets
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: jupyterlab-galata-test-assets
          path: |
            galata/test-jupyterlab-results
            galata/test-results

      - name: Upload Galata Test report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: jupyterlab-galata-report
          path: |
            galata/playwright-report
```
